- client: besu
  nametag: 4844-git
  dockerfile: git
  build_args:
      github: hyperledger/besu
      tag: 4844-devnet-5b
      # TODO: Add devnet-6 ready branch

- client: erigon
  nametag: 4844-git
  dockerfile: git
  build_args:
      github: roberto-bayardo/erigon
      tag: eip-4844

- client: ethereumjs
  nametag: 4844-git
  build_args:
      baseimage: ethereumjs/ethereumjs-monorepo
      tag: master

- client: go-ethereum
  nametag: 4844-git
  dockerfile: git
  build_args: # TODO: add Marius back once updated
      github: spencer-tb/go-ethereum
      tag: hive-cancun-dvnt7

- client: nethermind
  nametag: 4844-git
  dockerfile: git
  build_args:
      github: NethermindEth/nethermind
      tag: feature/eip-4844-v6
