- client: besu
  nametag: 4844-git
  dockerfile: git
  build_args: # TODO: add hyperledger/besu @ 4844-devnet-5b once fixed
      github: spencer-tb/besu
      tag: hive-cancun-dvnt7

- client: erigon
  nametag: 4844-git
  dockerfile: git
  build_args: # TODO: add up to spec 4844 enable branch for erigon
      github: roberto-bayardo/erigon
      tag: eip-4844

- client: ethereumjs
  nametag: 4844-git
  build_args: # TODO: add ethereumjs/ethereumjs-monorepo @ master once fixed
      github: spencer-tb/ethereumjs-monorepo
      tag: hive-cancun-dvnt7

- client: go-ethereum
  nametag: 4844-git
  dockerfile: git
  build_args: # TODO: add Marius back once updated
      github: spencer-tb/go-ethereum
      tag: hive-cancun-dvnt7

- client: nethermind
  nametag: 4844-git
  dockerfile: git
  build_args:
      github: NethermindEth/nethermind
      tag: feature/eip-4844-v7
