- client: besu
  nametag: cancun-4844-only-git
  dockerfile: git
  build_args:
      github: hyperledger/besu
      tag: master

- client: ethereumjs
  nametag: cancun-4844-only-git
  build_args:
      baseimage: ethereumjs/ethereumjs-monorepo
      tag: master

- client: go-ethereum
  nametag: cancun-4844-only-git
  dockerfile: git
  build_args:
      github: ethereum/go-ethereum
      tag: 4844-devnet-6

- client: nethermind
  nametag: cancun-4844-only-git
  dockerfile: git
  build_args:
      github: NethermindEth/nethermind
      tag: master
