- client: besu
  nametag: cancun-4844-4788-git
  dockerfile: git
  build_args:
      github: hyperledger/besu
      tag: master # TODO: add branch

- client: ethereumjs
  nametag: cancun-4844-4788-git
  build_args:
      baseimage: ethereumjs/ethereumjs-monorepo
      tag: master # TODO: add branch

- client: go-ethereum
  nametag: cancun-4844-4788-git
  dockerfile: git
  build_args:
      github: ethereum/go-ethereum
      tag: master # TODO: add branch

- client: nethermind
  nametag: cancun-4844-4788-git
  dockerfile: git
  build_args:
      github: NethermindEth/nethermind
      tag: EIP-4788/BeaconStateRoot-in-EVM
